import time

REQUESTS_COMPLETED = 0;
PHP_REQUESTS_COMPLETED = 0;
TOTAL_REQUESTS = 0;
TOTAL_SALES_PARSED = 0;
PHP_REQUESTS_FAILED = 0;
RETRIED_REQUESTS = 0;

LAST_RESPONSE = "";

START_TIME = time.time();
