{
 "title": "Docker Containers",
 "description": "Simple exporter for cadvisor only",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!=\"ffmt_grafana\", name!=\"ffmt_promtail\", name!=\"ffmt_prometheus\", name!=\"ffmt_loki\", name!=\"portainer\", name!=\"ffmt_pma\"}[5m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!=\"ffmt_grafana\", name!=\"ffmt_promtail\", name!=\"ffmt_prometheus\", name!=\"ffmt_loki\", name!=\"portainer\", name!=\"ffmt_pma\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$host\", name=~\"$container\", name=~\".+\", name!=\"ffmt_grafana\", name!=\"ffmt_promtail\", name!=\"ffmt_prometheus\", name!=\"ffmt_loki\", name!=\"portainer\", name!=\"ffmt_pma\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "(time() - container_start_time_seconds{instance=~\"$host\",name=~\"$container\",name=~\".+\"})/86400",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}