#
# Redis Dockerfile
#
# https://github.com/dockerfile/redis
#

# Pull base image.
FROM mtvirux/redis-stack-server-python3.10:latest

COPY ./docker/redis /server

#Install required python modules
RUN pip3.10 install websocket && \
pip3.10 install websocket-client && \
pip3.10 install bson && \
pip3.10 install pymongo && \
pip3.10 install redis

WORKDIR /server

EXPOSE 80