#
# MTVirux Redis Dockerfile
#
#

# Pull base image.
FROM mtvirux/redis-stack-python:R702rc3-p3.10.5

COPY ./docker/redis/ /

WORKDIR /server

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/usr/local/bin/startup.sh"]