#
# MTVirux Redis Dockerfile
#
#

# Pull base image.
FROM mtvirux/redis-stack-python3.10

COPY ./docker/redis/ /

RUN chmod +x /entrypoint.sh

RUN chmod +x /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/redis_memory_cleaner.sh

RUN chmod +x /server/workers/mem_monitor.sh
RUN chmod +x /server/workers/run_server.sh

RUN chmod +x /server/workers/status_updater.sh

RUN chmod +x /monitor_server.sh

WORKDIR /server

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/usr/local/bin/startup.sh"]