services:
  ffmt_backend:
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - Scylla__ContactPoints__0=${SCYLLA_PRIVATE_IP}

  ffmt_ws_worker:
    environment:
      - Scylla__ContactPoints__0=${SCYLLA_PRIVATE_IP}

  ffmt_node_exporter:
    environment:
      - HOST_PRIVATE_IP=${APP_PRIVATE_IP}
