#
# MTVirux Redis Dockerfile
#
#

# Pull base image.
FROM mtvirux/redis-stack-python3.10

COPY ./docker/redis/ /

RUN chmod +x /entrypoint.sh
RUN chmod +x /usr/local/bin/startup.sh
RUN chmod +x /usr/local/bin/redis_memory_cleaner.sh

WORKDIR /server

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/usr/local/bin/startup.sh"]