FROM oberd/php-8.0-apache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN rm -rf /var/www/html/index.html
WORKDIR /etc/apache2/
COPY ./docker/backend/ /
COPY ./backend/ /var/www/html/
WORKDIR /var/www/html/
RUN rm -rf /var/www/html/.git
RUN rm -rf /var/www/html/docker
RUN rm -rf docker-compose.yml
RUN rm -rf Dockerfile
RUN a2enmod rewrite
RUN chmod +x /usr/local/bin/run_entrypoints.sh
CMD ["/usr/local/bin/run_entrypoints.sh"]