FROM nimmis/apache-php7
RUN apt-get update && apt-get install php7.0-mbstring php7.0-dom php7.0-zip php-geoip git nodejs npm php-memcache php-zip php-tidy -y
RUN rm -rf /var/www/html/index.html
WORKDIR /etc/apache2/
COPY ./docker/app /
COPY . /var/www/html/
WORKDIR /var/www/html/
RUN rm -rf /var/www/html/.git
RUN rm -rf /var/www/html/docker
RUN rm -rf docker-compose.yml
RUN rm -rf Dockerfile
RUN a2enmod rewrite
CMD ["run_entrypoints.sh"]