FROM mtvirux/php8-cassandra-mysqli-apache:ssl

#COPY FILES FROM REPO TO CONTAINER
COPY ./docker/backend/ /

WORKDIR /var/www/html/

#INITIATE CONTAINER
RUN chmod +x /usr/local/bin/run_entrypoints.sh
CMD ["/usr/local/bin/run_entrypoints.sh"]