global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
- job_name: ffmt
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - ffmt_prometheus:9090

- job_name: node_exporter
  static_configs:
  - targets:
    - ffmt_node_exporter:9100

- job_name: cadvisor
  static_configs:
  - targets:
    - ffmt_cadvisor:8080

- job_name: 'scylla'
  static_configs:
    - targets: ['ffmt_scylla:9180']
  metrics_path: '/metrics'
  scrape_interval: 15s
  scrape_timeout: 10s
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: ffmt_scylla:9180