server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:${LOKI_HOST_HTTP_PORT}/loki/api/v1/push

scrape_configs:
#BACKEND MONITORING
- job_name: backend
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/backend/*log
#DOCKER CONTAINER MONITORING
- job_name: docker
  static_configs:
  - targets:
      - ffmt_loki
    labels:
      job: docker
      __path__: /var/lib/docker/containers/*/*.log
#REDIS MONITORING
- job_name: redis
  static_configs:
  - targets:
      - ffmt_loki
    labels:
      job: redis
      __path__: /var/log/redis/*/*log