<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>WsWorker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\backend\Ffmt.Core\Ffmt.Core.csproj" />
  </ItemGroup>

</Project>
